config/routes.rb
Rails.application.routes.draw do
  resources :games, only: %i[create show index] do
    post :play, on: :member
  end

  root to: 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  TOTAL_ERRORS_ALLOWED = 7

  belongs_to :word

  scope :sorted, -> { order(created_at: :desc) }

  def errors_letters
    guesses - normalized_letters
  end

  def errors_made
    errors_letters.length
  end

  def errors_allowed
    TOTAL_ERRORS_ALLOWED - errors_made
  end

  def letters_to_guess
    letters.map do |letter|
      letter if guesses.include?(normalize_letter(letter))
    end
  end

  def lost?
    errors_allowed.zero?
  end

  def normalize_letter(letter)
    case letter
    when "Ё"
      "Е"
    when "Й"
      "И"
    else
      letter
    end
  end

  def normalized_letters
    letters.map { |letter| normalize_letter(letter) }
  end

  def over?
    won? || lost?
  end

  def play!(letter)
    unless over? || guesses.include?(normalize_letter(letter))
      guesses << normalize_letter(letter)
    end
  end

  def won?
    (normalized_letters - guesses).empty?
  end

  def letters
    word.letters
  end
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :games, dependent: :destroy

  validates :text, presence: true, uniqueness: true, format: { with: /\A[[:word:]]+\z/ }

  def letters
    text.chars
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    word = Word.order('RANDOM()').first
    game = word.games.create

    redirect_to game
  end

  def show
    @game = Game.find(params[:id])
  end

  def index
    @games = Game.sorted
  end

  def play
    game = Game.find(params[:id])
    game.play!(params[:letter])
    game.save

    respond_to do |format|
      format.json do
        render json: {
          current: render_to_string(partial: 'games/current', locals: { game: game }, formats: [:html])
        }
      end
    end
  end
end

app/helpers/game_helper.rb
module GameHelper
  def word_to_show(game)
    result =
    game.letters_to_guess.map do |letter|
      if letter.nil?
        "__"
      else
        letter
      end
    end

    result.join(" ")
  end

  def errors_to_show(game)
    game.errors_letters.join(" ")
  end
end

app/views/games/_current.html.erb
<p><%= word_to_show(game) %></p>

<p>Ошибки (<span id="errors-made"><%= game.errors_made %></span>): <%=
  errors_to_show(game) %></p>

<p>У вас осталось ошибок: <%= game.errors_allowed %></p>

<% if game.won? %>
  <p>Поздравляем, вы выиграли!</p>
<% elsif game.lost? %>
  <p>Вы проиграли, загаданное слово: <%= game.word.text %></p>
<% end %>

app/views/games/_game.html.erb
<li>
  <%= link_to l(game.created_at, format: :long), game %>
</li>

app/views/games/index.html.erb
<%= image_pack_tag 'Hangman.jpg', size: '200x200', alt: 'Hangman' %>
<h1>Hangman</h1>

<ul>
  <%= render @games %>
</ul>

<div class="mt-3">
  <%= button_to 'Новая игра', games_path, method: :post, class: 'btn btn-primary' %>
</div>

app/views/games/show.html.erb
<h1>Game #<%= @game.id %></h1>

<svg height="250" width="200" class="figure-container">
  <!-- Rod -->
  <line x1="60" y1="20" x2="140" y2="20" />
  <line x1="140" y1="20" x2="140" y2="50" />
  <line x1="60" y1="20" x2="60" y2="230" />
  <line x1="20" y1="230" x2="100" y2="230" />

  <!-- Head -->
  <circle cx="140" cy="70" r="20" class="figure-part" id="errors-1" />
  <!-- Neck -->
  <line x1="140" y1="90" x2="140" y2="120" class="figure-part" id="errors-2" />
  <!-- Body -->
  <line x1="140" y1="120" x2="140" y2="150" class="figure-part" id="errors-3" />
  <!-- Arms -->
  <line x1="140" y1="120" x2="120" y2="100" class="figure-part" id="errors-4" />
  <line x1="140" y1="120" x2="160" y2="100" class="figure-part" id="errors-5" />
  <!-- Legs -->
  <line x1="140" y1="150" x2="120" y2="180" class="figure-part" id="errors-6" />
  <line x1="140" y1="150" x2="160" y2="180" class="figure-part" id="errors-7" />
</svg>

<div id="current-status">
  <%= render 'current', game: @game %>
</div>

<%= form_with url: play_game_path(@game), id: 'play-form' do |f| %>
  <div class="form-group">
    <%= f.text_field :letter, class: "form-control", placeholder: "Введите букву и нажмите Enter" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>HangmanRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>